// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            int32
	Email         string
	Name          string
	Password      pgtype.Text
	OauthProvider pgtype.Text
	OauthID       pgtype.Text
}
